### ISSUE TITLE
Tango 2 possible?

### ISSUE THREAD

**Issue by TheSpirit** [moschotto/OpenTX_GPS_Telemetry#10]
HI.
Can you make it available for tango 2?
Thanks

**Comment by moschotto** [comment]
Tango isn’t officially supported by OpenTX  (and  opentx companion doesn‘t work). So  I can’t use the companion simulator to adapt the scripts and I don’t own a tango...

**Comment by TheSpirit** [comment]
I just tried the X9 lite version and it works. 
but it doesn’t look nice since the resolution of the tango 2 is 128x96. So everything is on Top and on the bottom there is some empty space.

**Comment by moschotto** [comment]
Can you share a picture please ?

**Comment by TheSpirit** [comment]
Sure

![15529830-7DE2-4562-A4A0-4006FB1625AD](https://user-images.githubusercontent.com/6056918/106361184-de9d0a80-631c-11eb-91dd-3a9ba769adae.jpeg)

**Comment by moschotto** [comment]
rename from .txt to .lua - as mentioned i don't own a tango... let me know how it goes and update a screen. 

BTW did you try if the scipt works in general?

[tango.txt](https://github.com/moschotto/OpenTX_GPS_Telemetry/files/5898319/tango.txt)

**Comment by TheSpirit** [comment]
Looks good. 
![AA8EDF2B-75CE-42AE-BFF2-BDCCDCDE2601](https://user-images.githubusercontent.com/6056918/106364181-68ed6a80-632d-11eb-9fe1-f095b881be5a.jpeg)
Will send a new screenshot tomorrow with real data.

**Comment by TheSpirit** [comment]
Everything seems fine. Just tested it outdoors. But the viewer seems not to work properly. After looking into the GPSpositions.txt I could see that not every line has a number and a timestamp. 
the second thing is, I am not sure what every line is showing me in the telemetry screen. Could you explain it to me in detail? With a picture?
Would be great. 
Thanks

**Comment by moschotto** [comment]
Please upload a screenshot of both an mask your coordinates. Then I can take a look and upload the script to the repository. Thanks

**Comment by TheSpirit** [comment]
Everything looks fine now. 

![9566FB34-A5BA-48BF-923D-78DC5235A793](https://user-images.githubusercontent.com/6056918/106389497-cf34c480-63e3-11eb-8cd6-0fa645e2fee2.jpeg)

The viewer also works fine now (was my fault with messed up txt file). 
could you adopt the viewer script to the bigger size of the tango 2 screen? Maybe an empty line between the gps position lines. 

![75C4D572-141A-4D57-A1A1-8E8C8FCEA706](https://user-images.githubusercontent.com/6056918/106389481-c80db680-63e3-11eb-980d-f17fab69e149.jpeg)

**Comment by moschotto** [comment]
here you go - see attached and rename. Please provide updated screenshots if possible. I need pics for the main page (detailed and on where you see the tango 2)

Thanks


[GPSviewerT.lua.txt](https://github.com/moschotto/OpenTX_GPS_Telemetry/files/5900128/GPSviewerT.lua.txt)
[GPSxT.lua.txt](https://github.com/moschotto/OpenTX_GPS_Telemetry/files/5900129/GPSxT.lua.txt)

**Comment by TheSpirit** [comment]
looks good

![IMG_1171](https://user-images.githubusercontent.com/6056918/106432015-65adc800-646e-11eb-9192-5f6043e28dbf.jpg)

**Comment by moschotto** [comment]
Thanks - can you please take a pic of the Controller with the script Running / the viewer AND the regular script an. If possible don’t mask everything- I.e.  just the first 3 values ?

**Comment by TheSpirit** [comment]
i do not get exactly which 3 pictures.
What is the "regular" script?
You have only 2 scripts.

**Comment by moschotto** [comment]
can you please share the following?

Pic of viewer running 
Pic of the telemetry script running 

I need some pics for the GitHub start page. 2 pics like

![89717D10-85C7-44E1-ABAF-5B603B1EF0F3](https://user-images.githubusercontent.com/10543292/106435406-233aba00-6473-11eb-8a10-14c6ede8f897.jpeg)

Thanks

**Comment by txbone66** [comment]
They suggested that I reach out to you.  Can you tell me how you got this working on your Tango 2?  
I have the following in my Telemetry path:
<img width="631" alt="Screen Shot 2021-05-18 at 10 57 03 AM" src="https://user-images.githubusercontent.com/16477443/118684383-c8ca2d00-b7c7-11eb-803f-0cd4ea9c8dff.png">

but when I create a page to run that script, I get an error.  They are trying to help me with this on #16

![IMG_2129](https://user-images.githubusercontent.com/16477443/118684509-e5fefb80-b7c7-11eb-9c0c-52feb1de974a.JPG)

**Comment by txbone66** [comment]
Just FYI, I downloaded this Tango.txt, looked inside, moved my GPSPositions.txt to the Logs folder and then changed it to Lua and it works!@!

**Comment by kirilldmt** [comment]
i updated my tango, and now i cant open script - its says Script syntax error TELEMETRY/GPSxT.lua:58 attempt to perform arith....
When drone not turned on, script opening ok
