### ISSUE TITLE
Horus X10 installation problem

### ISSUE THREAD

**Issue by slopingoff** [moschotto/OpenTX_GPS_Telemetry#12]
I have installed Gps folder containing BMP folder and main lua into Widget folder (I also tried installing into widget/t16/gps/and did not work)

I copied GpsviewerT16lua to the /SCRIPTS/TOOLS folder (I also tried another installation to leave a copy in the widget folder within GPS folder and did not work) 

None of the options I tried worked on Horus x10 .

What am I missing or not understanding properly?

Should it be" /T16/GPS" in the widget folder (or GPS/T16/GPS)and GPSviewerT16.lua in the /SCRIPTS/TOOLS only (not also in the widget folder.

**Comment by moschotto** [comment]
As described on the start page:

Install Jumper/HOROUS models:

copy the GPS folder (inculding subfolders) to /WIDGETS/GPS

copy GPSviewerT16.lua to /SCRIPTS/TOOLS

Setup "1/2" widget screen and select "GPS"



You can check this video as well
https://youtu.be/mqYcgPZe1KE
