### ISSUE TITLE
Emergency mode Horus X10

### ISSUE THREAD

**Issue by slopingoff** [moschotto/OpenTX_GPS_Telemetry#13]
Installed the lua script okay however when Setting up "1/2" widget screen and scrolling through to GPS widget, if I scroll past other lua widgets (i.e yapuu telemetry or 'Tadango'  graph widget) the transmitter enters emergency mode.

**Comment by moschotto** [comment]
Memory issue of your radio or FW you are using. Too many features or widgets enabled. Check this thread https://github.com/moschotto/OpenTX_GPS_Telemetry/issues/11

**Comment by moschotto** [comment]
Works for other users like this one: https://github.com/moschotto/OpenTX_GPS_Telemetry/issues/9

**Comment by slopingoff** [comment]
> 
> 
> Works for other users like this one: #9

Unfortunately It still does not explain why my installation causes Emercency  mode  only when installing this widget .I have installed Yaapus mapping widget lua (which is the only addition to my previous installation)and that does not cause emercency mode when selecting that or any other widget.
It is a shame because I like your widget as it is very well laid out lua but I cannot risk causing this emergency mode surely if the widget causes an eror it should shut down and not cause an error on the whole radio?

**Comment by moschotto** [comment]
Sorry I can’t solve your problem and seems not to be the „out of display range“ problem because it works for other users with x10s. 

Try to do a clean setup and use a FW with only the features enabled you REALLY need. I don’t own a x10 and the simulator doesn’t throw any exceptions.

could be a SD card issue as well. Try comment the write logfile section 


			--write logfile		
			file = io.open(log_filename, "a")    									
			io.write(file, wgt.coordinates_current ..",".. time_power_on ..", "..  wgt.gpsSATS, "\r\n")		
			io.close(file)
