### ISSUE TITLE
Homeposition is set incorrectly

### ISSUE THREAD

**Issue by jogybaer0815** [moschotto/OpenTX_GPS_Telemetry#14]
thank you for your useful app.
In most cases (>95%) i have a wrong home position fix, which is often hundreds of kilometers away from my location. this affects several drones and the Radiomaster TX16 and Horus X10S equally.
Is it possible to check the first position values for consistency and discard incorrect values?
many greetings, jörg

**Comment by moschotto** [comment]
Hi - make sure you reset the telemetry once you have a valid GPS fix. This resets the home position.

**Comment by jogybaer0815** [comment]
Thanks for this hint. Is there a possibility to do gps telemetry reset automatically after first fix throught lua?
