### ISSUE TITLE
script syntax error bad argument #1 to "write... on x9 lite

### ISSUE THREAD

**Issue by P-I-Engineer** [moschotto/OpenTX_GPS_Telemetry#15]
opentx 2.3.10
crsfire/elrs
inav

i'm getting this error. Script appears to work, then crashes. Sometimes the tools folder appears empty after.

thanks, very cool script

**Comment by moschotto** [comment]
You mean line 15?

/LOGS/GPSpositions.txt

Do you have /LOGS folder on the SDcard?

**Comment by P-I-Engineer** [comment]
ok, that worked adding a LOGS folder, i did not have one.

i still have an issue where my sd card crashes or something. My tools and sd card page are blank. you heard of that?

**Comment by moschotto** [comment]
No sorry - no idea but try to minimize the enabled features. Just enable the things you really need. Memory issues (RAM) seem to be common but I’m not sure if this can lead to SD problems
