### ISSUE TITLE
Error on Tango 2

### ISSUE THREAD

**Issue by txbone66** [moschotto/OpenTX_GPS_Telemetry#16]
I'm on FreedomTX 1.25.  I've added the GPSxT.lua and the BMP folder (with its contents) to the scripts/telemetry path and put GPSviewerT.lua in the scripts/tools folder.  I've added the script to a page, but when I go to that page, it says Script Syntax error TELEMETRY/GPSxT.lua:7 unexpected symbol near...  but then I can't read any more...  any suggestion?

**Comment by moschotto** [comment]
Which line does throw an error? Line 7 is actually a comment ?!

make sure that the /LOGS/ folder exists

Can you check this?

**Comment by txbone66** [comment]
The error on the screen is not complete.  Hoping these images can come across.  One just shows my folder where the script is located, the one shows the error message when I scroll to the page where I’m calling the script, and the setup screen pointing to the script.

**Comment by moschotto** [comment]
Did you upload an pictures/ screens? I don’t own a tango 2 but this user / thread reported that it works... maybe you want to ask him for his setup?

and did you check that the logs folder exists? -> /LOGS 

https://github.com/moschotto/OpenTX_GPS_Telemetry/issues/10

**Comment by txbone66** [comment]
![IMG_2129](https://user-images.githubusercontent.com/16477443/118673097-5a34a180-b7be-11eb-80ec-f3c09fcae0d7.JPG)
![IMG_2130](https://user-images.githubusercontent.com/16477443/118673119-5ef95580-b7be-11eb-9e4f-3b75036f0a0b.JPG)
![IMG_2132](https://user-images.githubusercontent.com/16477443/118673125-5f91ec00-b7be-11eb-9a7d-3df004ab4e84.JPG)
There are the three pics I was trying to attach.

**Comment by txbone66** [comment]
/Logs does exist, but there is only a readme.txt in that folder.

**Comment by moschotto** [comment]
Open the GPSxT.lua in a text editor an remove the whole comment section, save it and try again - let’s see which line throws an error

BTW the gpspositions.txt should be in the LOGS folder respectively will be stored in the logs folder.

**Comment by txbone66** [comment]
FYI must have been that logs file...  sorry for the trouble...  but now it's working for me.
