### ISSUE TITLE
Just a question about GPSviewer

### ISSUE THREAD

**Issue by dsysoyev** [moschotto/OpenTX_GPS_Telemetry#17]
Could you please display latest results at the first position in GPSviewer, it takes long time to get them.

**Comment by moschotto** [comment]
open the GPSviewer.lua in a text editor and replace this :


              --read file contents into array/table
		for line in string_gmatch(buffer, "([^\n]+)\n") do			
			coordinates[linectr] = line	
			print("GPS_Debug_1",linectr, coordinates[linectr])	
			linectr = linectr + 1		
		end	

with this

              --read file contents into array/table
		for line in string_gmatch(buffer, "([^\n]+)\n") do			
			coordinates[linectr] = line	
			print("GPS_Debug_1",linectr, coordinates[linectr])	
			linectr = linectr + 1		
		end	


		--reverse array/table contents
		coordinates_tmp = {}
		for k in pairs (coordinates) do coordinates_tmp[k] = coordinates[k] end
		j=0
		for i = linectr,1,-1 do		
			 coordinates[j] = coordinates_tmp[i-1]
			 j = j + 1
		end	


check the displayed time on top left if it works. 

Sorry, currently i have no time to adjust ALL the files for all radios...
