### ISSUE TITLE
Syntax error in GPSviewerX9L.lua

### ISSUE THREAD

**Issue by febbyeka** [moschotto/OpenTX_GPS_Telemetry#19]
Handset Jumper T12
TX Happymodel ExpressLRS 2.4
opentx 2.3.14

Downloaded and installed X7_X9lite version
Telemetry LUA is working well
GPSviewerX9L said "no GPSPositions.txt..." if there's no log file
After few flight, GPSPosistions.txt created. But there was syntax error when GPSviewerX9L LUA opened.
Attached GPSPositions.txt
[GPSpositions.txt](https://github.com/moschotto/OpenTX_GPS_Telemetry/files/7611879/GPSpositions.txt)

**Comment by febbyeka** [comment]
After some more flies, for some reason GPSViewer is working, there is no syntax error. The coordinate is showed, but I can't scroll up or down. So basically just see four lines.
Attached gpspositions.txt
[GPSpositions.txt](https://github.com/moschotto/OpenTX_GPS_Telemetry/files/7613087/GPSpositions.txt)

**Comment by moschotto** [comment]
works for me wtih the T16 simulator

![Screenshot 2022-02-11 223108](https://user-images.githubusercontent.com/10543292/153673382-b9f1144d-d79c-449d-a6e3-bfb5fe9a1da2.jpg)


![gpsviewer](https://user-images.githubusercontent.com/10543292/153673256-91f2c895-c7cc-4e94-93c1-2b601ce378c1.gif)
