### ISSUE TITLE
Log Viewer cant scroll  Jumper T12

### ISSUE THREAD

**Issue by febbyeka** [moschotto/OpenTX_GPS_Telemetry#20]
Radio : Jumper T12
FW : EdgeTX 2.5.0
GPS Position Viewer v1.1 can't scroll down. Cursor only stays at first line. Tried all buttons, but cursor not move
[GPSpositions.txt](https://github.com/moschotto/OpenTX_GPS_Telemetry/files/7912082/GPSpositions.txt)

**Comment by moschotto** [comment]
try again - tested in simulator only

https://github.com/moschotto/OpenTX_GPS_Telemetry/tree/main/T16_EdgeTX
