### ISSUE TITLE
Request for Imperial miles vs. km for distance

### ISSUE THREAD

**Issue by roligmue** [moschotto/OpenTX_GPS_Telemetry#21]
Hi,

You gave a couple edits to get this working a while ago; display miles vs. kilometers. I had it working until i installed updates with the newer releases of the GPS Telemetry. I've since been just leaving it at kilometers which works fine.

My last attempt I was able to get Distance from home to display a Miles distance. It's the Total distance that stays at 0 in the widget. It all works fine for me otherwise.

Would you be able to share something that could get Miles displaying again?

FrSky X10s
OpenTx 2.3.14
GPS LUA Telemetry 2.3.2

Thank you

**Comment by moschotto** [comment]
Hi, you can try to modify the calc_distance function. Convert the km to mi:

Replace this
local dist = (6371000 * c) / 1000

With
local dist = ( (6371000 * c) / 1000) / **1.609344**

https://www.rapidtables.com/convert/length/km-to-mile.html

Example
Convert 20 kilometers to miles:
d(mi) = 20km / 1.609344 = 12.42742mi

let me know if this works for you

**Comment by roligmue** [comment]
Hi,

I am able to get Mph calculated properly. But, I'm questioning the accuracy of the Total Distance.

What I'm seeing is that just the Total Distance calculated seems to be off, if using either calculating km or miles. I checked multiple times using each, and basing the distance accuracy using the odometer on my truck to do the measurements driving away and back on a straight road.

The Distance to Home works really well matching the odometer.

However, the calculations for the Total Distance is always way low comparing to the odometer reading on my pickup. Also, it is way low for instance even as I'm driving away from my starting position, as it should count up with a similar distance to the Distance to Home as I'm moving away.

I reset the drone, radio, and also used the Reset telemetry  function along with the flight reset to be sure there was a good starting point in the Gps Log.

I did a diff on the main.lua file that is on my radio and it matches the same of the v2.3 I had downloaded.

Thoughts?

Thank you

**Comment by moschotto** [comment]
If I am testing it with the simulator it works fine,- if moving away from the home-position in straight line, the dist home equals the total distance. even on a test path it works fine:

<br/>

![Screenshot 2022-02-09 232757](https://user-images.githubusercontent.com/10543292/153303605-b33a0ab9-200b-48c4-aceb-36486ebf4c9b.jpg)


the problem occurs if i replay the log in 5x speed -> the distance is off. this is because the telemetry is updated once a second and not faster. in other words, some coordinates between "old" and the new/current "location" are missing. 

this causes the calculation issues - for example:


![Untitled](https://user-images.githubusercontent.com/10543292/153303398-ba681bbe-ed82-423b-9117-982c26988db1.jpg)

Distance to home works because it always calculates the current position to the “fixed” home position. 

Let me know how much the total dist is off in your case

**Comment by roligmue** [comment]
Hi,

I did a few tests. Kind of different distances it seems, but here's my last results attached. I since looked at the log file, not sure why it's truncated to just 2 lines on this one. I can do another test run tomorrow if that doesn't help you...

FYI, I turned off all telemetry logging on opentx. I was logging the telemetry metrics. I also deleted all the display pages on the X10s radio too, so now the only display screen on the radio is now the GPS LUA.

Test setup steps:
- drone power off and X10s radio off
- turned X10s radio on
- drone power on, power provided by USB port to the flight controller
- waited for satellite lock, etc.
- drove straight line then turned off drone
- turned off X10s radio
![IMG_8205](https://user-images.githubusercontent.com/78124234/153308509-44813e17-2e02-4de9-a310-d2a0ad203b30.jpg)
![IMG_8206](https://user-images.githubusercontent.com/78124234/153308511-db51047e-7e88-4de1
[GPSpositions.txt](https://github.com/moschotto/OpenTX_GPS_Telemetry/files/8036844/GPSpositions.txt)
-bb8a-1367380ce43f.jpg)
o

**Comment by roligmue** [comment]
Here's the GPS Screen at the end of my test drive

![IMG_8206](https://user-images.githubusercontent.com/78124234/153308747-4fe873bb-c1ac-4e38-b4e0-51d0f3b7685e.jpg)

**Comment by roligmue** [comment]
[GPSpositions.txt](https://github.com/moschotto/OpenTX_GPS_Telemetry/files/8036868/GPSpositions.txt)

**Comment by roligmue** [comment]
Hi,
Looking at some things in OpenTx as your timing example of updates got me thinking.

I see some update indications on in my OpenTx that may be contributing to the Total Distance calculations being off; kind of like you described.

Take a look at these short videos from my X10s.
I'm using Crossfire and my X10s has a circuit board mod installed that allows a higher baud rate that was to be able to run at the full speed of crossfire and its telemetry updates.
https://blog.seidel-philipp.de/fixed-inverter-mod-for-tbs-crossfire-and-frsky-qx7/

Anyway, maybe this helps you some by sharing these shorts videos. Note how the timing of the quad location updates are not really at 1 sec. intervals on the GPS LUA. Some are, some are not. Some are are pretty fast times.

I always thought that asterisks on the telemetry page was related to refreshing the data.  

For these, I was just running the quad plugged into USB port on table in the house.

https://user-images.githubusercontent.com/78124234/153318561-5a84ca02-7ac2-45fb-94cc-257b1f5584ca.MOV

https://user-images.githubusercontent.com/78124234/153318597-75f0bb1f-6a60-470e-a5ed-4f2112f735be.MOV

**Comment by moschotto** [comment]
retested it with my setup and betaflight instead of using the companion simulator. my x9 lite doesn't need an inverter and my crossfire baud rate was already set to 400k 

- GPS runs at 57600 baud in betaflight
- protocol NEMA, no autobaud, no auto config
- rest is default config

after testing the same path 5 times (see video - actually your provided coordinates), it is off by 0.08km / 0.049 miles.
start and pause the video - you can see a perfect match between home and total distance. the path total length is 2000m


https://user-images.githubusercontent.com/10543292/153489685-2f756b15-f408-4432-a2c8-866051268b69.mp4

check out the test-path with provided nmea file here:
https://www.nmeagen.org/
[minneapolis.zip](https://github.com/moschotto/OpenTX_GPS_Telemetry/files/8044029/minneapolis.zip)

so it must be something wrong with your setup. GPS configuration, GPS reception or telemetry.
No other ideas currently  - even with my test-setup, the coordinates will be send via UART/SERIAL with a 10ms delay, so this couldn't be issue either....

**Comment by moschotto** [comment]
if you have an arduino you can simulate the same path/thing as I did. Simply connect GND and TX of the arduino to the flight ctrl GND and RX and replay the coordinates… I can provide the ino file if you want.

if this works for you, you know that it is not the radio nor the telemetry

**Comment by roligmue** [comment]
Hi,

Some more testing attached with interesting results.

Did some thinking over night and a little internet browsing gave me something to try. I don't have at arduino at this point.

Summary:
I think the source of the error calculation is related to the Crossfire RF Profile link in use at the time, their updating of the telemetry metrics, plus their telemetry metric groupings by priority on update timings.

This one in particular was interesting to drive what I tested this morning. 
Kinda, validates some what I'm experiencing.
https://discuss.ardupilot.org/t/passthrough-telemetry-over-crsf-crossfire/62668

My test setup was the same, driving a straight line, doing this 2x with the same results.
1) If I set Crossfire to RF profile 50Hz, the updates of the non-critical telemetry metrics, like the GPS ones, as viewed through the OpenTx telemetry page are like a constant 1 sec heartbeats as watching the asteriks.
The Total Distance then matches the Distance from home - as I drive, and at the end.

2) If I set the Crossfire RF profile to Dynamic or 150Hz, the updates of the non-critical telemetry metrics, like the GPS, as viewed through the OpenTx telemetry page, are kind of all over the place as watching the asteriks, like I shared in a previous comment. 
The Total Distance now does not match the Distance from home - as I drive, nor at the end. And is always a lot lower.

I knew flying in RF Profile Dynamic affected some things, but thought it was more related to flight control latency.

See pics and video attached:
=======
![IMG_8218](https://user-images.githubusercontent.com/78124234/153628713-e85de297-0483-4bf6-9443-c49da1074561.jpg)
![IMG_8219](https://user-images.githubusercontent.com/78124234/153628729-0580b95f-91fd-4239-ae3c-00319251c45b.jpg)
====
![IMG_8220](https://user-images.githubusercontent.com/78124234/153628732-7396cea8-73db-4236-bcda-d9877dd10bc2.jpg)
![IMG_8221](https://user-images.githubusercontent.com/78124234/153628739-55551dfe-2e0c-4684-a7a4-f9134a00b791.jpg)
====
![IMG_8224](https://user-images.githubusercontent.com/78124234/153628844-e4bdc106-e574-42a9-bb4d-04d127601daa.jpg)
![IMG_8225](https://user-images.githubusercontent.com/78124234/153628864-94b939f5-7701-468d-866d-cdf8ed57f4ca.jpg)
====
![IMG_8226](https://user-images.githubusercontent.com/78124234/153628988-3975b119-5c49-4860-8154-23f20cfd0bab.jpg)
![IMG_8222](https://user-images.githubusercontent.com/78124234/153628972-be5310db-918d-463e-b359-0a7bb57555d9.jpg)

https://user-images.githubusercontent.com/78124234/153631363-4b39848c-5bb6-4f1a-be6a-a63b006e655b.MOV

**Comment by moschotto** [comment]
Ok thanks for the detailed summary. So basically not related to script but rather to the crossfire update frequency… I’m closing the issue now. Checking my setup / update frequency later and let u know

**Comment by roligmue** [comment]
Sounds good.

If Total Distance accuracy is important, for now I can set Crossfire RX Profile to 50Hz.

**Comment by moschotto** [comment]
just FYI - works for me with both rate profiles on OpenTX 2.3.14 Crsf shot:

crsf dynamic update:

https://user-images.githubusercontent.com/10543292/153657616-a0c6996c-740a-4866-9b32-35e32f2ea520.mp4

<br/>

crsf 150Hz update

https://user-images.githubusercontent.com/10543292/153657632-fcde418e-e094-4d25-aea6-facbe27fcb91.mp4
