### ISSUE TITLE
ANy chance of iBus for GPS please?

### ISSUE THREAD

**Issue by Mike-HRC** [moschotto/OpenTX_GPS_Telemetry#23]
Hi mosch, I now have the FrSky working nicely after Daniel made a change to th ehandling of GPS data.  Is there any chance that you could include support for FlySkt iBus GPS as well please - I have a number of FlySky receivers as well as FrSky an dit would be great to standardise on your widget.

Looking at Daniel's sensor info in his Arduino code - this is the format (the extra "alternative" sensors are needed to re-scale the Lat / Lon to match FrSky format.
    if (config.gps == true)
    {
        SensorIbus *sensorIbusP;
        Bn220 *gps;
        gps = new Bn220(GPS_SERIAL, GPS_BAUD_RATE);
        gps->begin();
        sensorIbusP = new SensorIbus(AFHDS2A_ID_GPS_STATUS, IBUS_TYPE_U16, gps->satP(), gps);
        addSensor(sensorIbusP);
        sensorIbusP = new SensorIbus(AFHDS2A_ID_GPS_LAT, IBUS_TYPE_S32, gps->latP(), gps);
        addSensor(sensorIbusP);
        sensorIbusP = new SensorIbus(AFHDS2A_ID_GPS_LON, IBUS_TYPE_S32, gps->lonP(), gps);
        addSensor(sensorIbusP);
        sensorIbusP = new SensorIbus(AFHDS2A_ID_GPS_ALT, IBUS_TYPE_S32, gps->altP(), gps);
        addSensor(sensorIbusP);
        sensorIbusP = new SensorIbus(AFHDS2A_ID_SPE, IBUS_TYPE_U16, gps->spdP(), gps);
        addSensor(sensorIbusP);
        sensorIbusP = new SensorIbus(AFHDS2A_ID_COG, IBUS_TYPE_U16, gps->cogP(), gps);
        addSensor(sensorIbusP);
        sensorIbusP = new SensorIbus(AFHDS2A_ID_CLIMB_RATE, IBUS_TYPE_S16, gps->varioP(), gps);
        addSensor(sensorIbusP);
        sensorIbusP = new SensorIbus(AFHDS2A_ID_GPS_DIST, IBUS_TYPE_U16, gps->distP(), gps);
        addSensor(sensorIbusP);
#ifdef IBUS_GPS_ALTERNATIVE_LAT_LON
        float lat = *gps->latP() / 10000.00;
        float lon = *gps->lonP() / 10000.00;
        sensorIbusP = new SensorIbus(AFHDS2A_ID_S84, IBUS_TYPE_S32, &lat, gps);
        addSensor(sensorIbusP);    
        sensorIbusP = new SensorIbus(AFHDS2A_ID_S85, IBUS_TYPE_S32, &lon, gps);
        addSensor(sensorIbusP);
#endif
    }

I also made a small change to the Drone imade - since I fly planes, hope you don't mind :)

Apologies if this is the wrong way to ask for this - I'll happily remove it if it is.

Cheers
![GPS image](https://user-images.githubusercontent.com/62241833/155552231-86942375-904b-4a58-8588-994c3a67f00a.jpg)

Mike

**Comment by moschotto** [comment]
Hi - sorry, but currently I have no time to dig into iBus telemetry
