### ISSUE TITLE
Jumper T-Pro reboot

### ISSUE THREAD

**Issue by Superiedy** [moschotto/OpenTX_GPS_Telemetry#25]
hello i tried to put your awesome project on my t-pro with edgetx, but it doesn't work properly when i open the tools gpx status it starts to restart the radio. how can i solve

**Comment by moschotto** [comment]
Please follow the installation instructions - use the right folders etc. I don’t own a t-pro so I can test only with the silmulator. Edgetx 2.6.0 should work. Please double check the release that you are using….

**Comment by Superiedy** [comment]
hi thanks for the quick reply. i checked and i have edgetx 2.7.0 can that be the problem? must it have version 2.6.0?

**Comment by moschotto** [comment]
please follow the install instructions again. Most recent EdgeTX version works as expected:

![grafik](https://user-images.githubusercontent.com/10543292/164995924-42baafb5-99d5-4481-8dee-b1362d7e9242.png)

ps: if there is no logfile (automatically generated by the GPS script) in the logs folder, you can’t use the stats viewer . Run the GPS script and check if the logfile is present

**Comment by Superiedy** [comment]
Grazie. Avevo notato che mi mancava il file TXT nella cartella log l'ho creato io manualmente, ma in seguito a questo mi si riavvia la radio appena riesco riprovo . È possibile che ho sbagliato qualcosa perché a me non genera il file TXT nella cartella log . Per ora grazie ti aggiorno
