### ISSUE TITLE
Imperial units?

### ISSUE THREAD

**Issue by tedsears** [moschotto/OpenTX_GPS_Telemetry#26]
Love the widget, using it edgtx 2.7.   Having the option to use imperial units (miles, feet) would be great if possible.

**Comment by moschotto** [comment]
Check this thread

https://github.com/moschotto/OpenTX_GPS_Telemetry/issues/9

**Comment by tedsears** [comment]
Thanks! 
Ted 

Sent from Yahoo Mail on Android 
 
  On Sat, Apr 30, 2022 at 13:07, ***@***.***> wrote:   


Check this thread

#9
