### ISSUE TITLE
GPS Log Max 84 Entrys

### ISSUE THREAD

**Issue by Topunzel** [moschotto/OpenTX_GPS_Telemetry#27]
Hello,

thank you for the nice script. It works very good on my Zorro, except that i have to delete the GPS-logfile manually when it reached 84 entrys. Otherwise it will stop recording my coordinates. Is this a bug?

Best regards

**Comment by moschotto** [comment]
Hi, can’t be because the logfile will be cleared if there are more than 99 entries (log rotation). you can adjust it if you want but don’t have to.



		if ctr >= 99 then
			ctr = 0				
			--clear log
			file = io.open(log_filename, "w") 
				io.write(file, "Number,LAT,LON,radio_time,satellites,GPSalt,GPSspeed", "\r\n")		
			io.close(file)	
			
			--reopen log for appending data
			file = io.open(log_filename, "a")    			
		end

**Comment by Topunzel** [comment]
Hello, the Problem is, there are never more than 84 entries 😅 it just stops when 84 are reached :)

**Comment by moschotto** [comment]
The try to set it 50 and retry again (just for testing)

**Comment by moschotto** [comment]
Works as expected - EdgeTX Zorro Simulator. Double check the telemetry on your quad / radio. As soon as you get a valid GPS fix the telemetry screen should automatically update.

![zorro](https://user-images.githubusercontent.com/10543292/169409547-a17a9d11-3f89-4816-95e0-80829fbc43c5.gif)
