### ISSUE TITLE
Display a QR code with coordinates

### ISSUE THREAD

**Issue by roscor61** [moschotto/OpenTX_GPS_Telemetry#28]
An idea:
Display a QR code on the tx with long/lat.  (update on demand) to simply use a phone to find on Google maps if you loose a model.
I don't know if exist a lib to link to do this.

Thanks
Rosario

**Comment by moschotto** [comment]
Already thought about it but it needs to much resources

For example:
https://github.com/teckel12/LuaTelemetry/issues/350

Another idea is a barcode that contains the coordinates but It won’t fit on screen (I.e on the 128x64 display models

**Comment by moschotto** [comment]
Or just use Google lens:

![A9AFE432-62FB-4020-B8D1-7BF3DA665596](https://user-images.githubusercontent.com/10543292/169815920-00518257-be3a-492c-9ed5-2ac422c4b9d8.gif)

**Comment by roscor61** [comment]
Great!

Thanks

Rosario

Il lun 23 mag 2022, 14:08 moschotto ***@***.***> ha scritto:
