### ISSUE TITLE
Arrow pointing to the aircraft position

### ISSUE THREAD

**Issue by kvng1** [moschotto/OpenTX_GPS_Telemetry#29]
Is it possible to have a small arrow on the screen pointing to the aircraft position by using transmitter's compass (thru spare uart https://abra-electronics.com/wireless/gps/modules/sens-gy-26-digital-compass-module.html)? It's super helpful in aiming antenna and in finding lost model.

**Comment by moschotto** [comment]
Hi - I think this is too much effort - adding additional hardware for just an arrow. The idea is to use the mobile phone as a “lost model finder” instead of the radio itself. 

Furthermore this would mean different releases for all supported radios

greetings
