### ISSUE TITLE
Script syntax error

### ISSUE THREAD

**Issue by saturn-fpv** [moschotto/OpenTX_GPS_Telemetry#30]
Hi moschotto,
I really dig your telemetry screen, but sometimes I have issued that I would like to ask you for help.

I run your lua script on a TBS Tango 2 and use script 2.3 (as 2.4 is the same for Tango). Sometimes I get this error on the screen, right when I start the widget.

> Script syntax error
> ?:0
> attempt to perform arith...

![20220722_192110_small](https://user-images.githubusercontent.com/61454345/180968698-51497197-9162-4cbf-95f7-2e5c2f702689.jpg)

Picture is attached. I have this issue sometimes but not always and I have not figured out when I get that and when not. It happens sometimes when the copter is connected, and sometimes even without the copter being connected.
What could be the cause?
I had the feeling, that while the copter was connected, it only worked after I got the number of satellites which I configured as minimum in Betaflight, but I can't say for sure.

Also on a side question: Is there a specific reason why the changes of 2.4 are not implemented for Tango display size?

Thanks so much for your help, and for this great tool!

**Comment by moschotto** [comment]
The issue cloud be related to the GPS coordinates- I believe the calculation of the distance won’t work if a ‘0 or nil value’ comes in. For me it looks like the input value/coordinates are scrambled -> “ attempt to perform arithmetic on a nil value ”. please double check with a good GPS fix - at least 6-7 satellites.


- Is there a specific reason why the changes of 2.4 are not implemented for Tango display size?

Simply no time :)
