### ISSUE TITLE
Scrolling in Log viewer.

### ISSUE THREAD

**Issue by LoakAudio** [moschotto/OpenTX_GPS_Telemetry#32]
Hi Mosch,
Using the last release x7_x9lite with a Jumper T-Lite, I cant scroll down the logs in the log viewer.
Is it possible  ? If not, could the last recorded position be the first displayed ?

Thank you

**Comment by moschotto** [comment]
fixed - check out;

https://github.com/moschotto/OpenTX_GPS_Telemetry/blob/main/x7_x9lite/

=> GPS Stats X9L.lua
