### ISSUE TITLE
Horis X12

### ISSUE THREAD

**Issue by WimSanders** [moschotto/OpenTX_GPS_Telemetry#33]
unfortunately I can't get it to work on my horus X12S. The program does not find my GPS. In Telemetry I see the GPS, ID 227.

**Comment by moschotto** [comment]
Please follow the installation instructions closely. Here is a setup video that you can check as well

https://youtu.be/mqYcgPZe1KE

If you encounter an script ERROR paste in a screenshot or the error message. 

Thanks

**Comment by WimSanders** [comment]
Thank you for the quick response,
I performed the setup exactly as described.
No error messages.
I used the T16 for my Horus X12S.
Open TX verse. 2.3.15.
![screen-2023-02-19-132640](https://user-images.githubu
![screen-2023-02-19-132713](https://user-images.githubusercontent.com/24661114/219945530-bca42a99-8cb3-4ce4-b6dc-1b8344860205.gif)
sercontent.com/24661114/219945263-235466bf-16fb-43d5-ae9d-cd73ae1378a1.gif)
![screen-2023-02-19-132640](https://user-images.githubusercontent.com/24661114/219945443-3d2f5cbf-521f-4a59-8bd4-3cc055eed0c2.gif)
on the left in black the internal GPS of Horis
On the right the GPS in the model

With kind regards
Wim

**Comment by WimSanders** [comment]
![screen-2023-02-19-132704](https://user-images.githubusercontent.com/24661114/219945767-530cadd1-330f-4353-909b-40aa15fc9786.gif)

**Comment by moschotto** [comment]
The problem is most likely caused by opentx or your radio setup. delete all sensors and rediscover them again

**Comment by WimSanders** [comment]
There is indeed something strange going on.
I have removed all sensors and re-searched
The ID remains the same
But when I view the sensor data I see different IDs compared to the overview

![sensor 8](https://user-images.githubusercontent.com/24661114/219958340-6aa37980-6bbc-4fee-866b-c07be66ddef0.gif)
![sensor 5](https://user-images.githubusercontent.com/24661114/219958354-dbd03a76-796d-494e-a1b5-43876acf7e5e.gif)
![sensor 6](https://user-images.githubusercontent.com/24661114/219958356-7df1c122-29ba-4de8-939a-80bffe208ce3.gif)
![sensors](https://user-images.githubusercontent.com/24661114/219958357-3143359c-3c6a-4c0d-a456-492549fa9f26.gif)
![sensor 1](https://user-images.githubusercontent.com/24661114/219958359-fa63749d-2807-4637-8476-a41f5a5b6278.gif)

**Comment by moschotto** [comment]
Tested with the simulator - works as expected. So it's not a script / ID problem because it looks the same in the sim......

IDs 0800, 0820, 0830


![image](https://user-images.githubusercontent.com/10543292/219969689-a8ebaad7-923d-4497-8f37-0adf0aa09312.png)




An d check if lua is enabled in your opentx version.... see "OPTS" in the screenshot

**Comment by WimSanders** [comment]
![screen-2023-02-19-212211](https://user-images.githubusercontent.com/24661114/219970520-dc7f6e8a-9d15-4712-a113-1c1beaf65ded.gif)

**Comment by moschotto** [comment]
sorry but i don't know why it's not working on your side? are you using ibus?

check this
https://github.com/moschotto/OpenTX_GPS_Telemetry/issues/23


what you can try is to write a separate logfile - (open the main.lua file with a text editor).  

Add "write_log(wgt)" to the **refresh** function


For example
```
	-- set the colours
	newtext_color = wgt.options.TextColor
	newline_color = wgt.options.LineColor	
	
	get_data(wgt) 	
	write_log(wgt)
```


Add the lines between DEBUG to the **write_log** function

```
	local function write_log(wgt)

		now = getTime()    
		if wgt.old_time_write + wgt.log_write_wait_time < now then
		
			wgt.ctr = wgt.ctr + 1		
			time_power_on = SecondsToClock(getGlobalTimer()["session"])
			

			--[DEBUG  ######################
			--write debug logfile
			file = io.open("/LOGS/GPS_debug.txt", "a")    									
			io.write(file, "GPS ID:" .. wgt.gpsId ..", Alt ID:".. wgt.gpsaltId  ..", Speed ID:".. wgt.gpsspeedId  ..",SAT ID:".. wgt.gpssatId  ..",LAT:".. wgt.gpsLAT  ..",LON:".. wgt.gpsLON  ..",Sats no:"..  wgt.gpsSATS..", Alt m:".. wgt.gpsALT ..", Speed kmh:".. wgt.gpsSpeed, "\r\n")					
			io.close(file)			
			--[DEBUG  #####################**

```


the logfile /LOGS/GPS_debug.txt should look like this:

![image](https://user-images.githubusercontent.com/10543292/219975409-6fa43b96-ed20-48c9-86dd-11448898acbe.png)

**Comment by moschotto** [comment]
you can also try this GPS widget just for testing 
https://github.com/kristjanbjarni/opentx-widgets#gps-widget-widgetsgpsmainlua

**Comment by WimSanders** [comment]
Like this?
		if wgt.old_time_write + wgt.log_write_wait_time < now then
		
			wgt.ctr = wgt.ctr + 1		
			time_power_on = SecondsToClock(getGlobalTimer()["session"])
			
			--[DEBUG  ######################
			--write debug logfile
			file = io.open("/LOGS/GPS_debug.txt", "a")    									
			io.write(file, "GPS ID:" .. wgt.gpsId ..", Alt ID:".. wgt.gpsaltId  ..", Speed ID:".. wgt.gpsspeedId  ..",SAT ID:".. wgt.gpssatId  ..",LAT:".. wgt.gpsLAT  ..",LON:".. wgt.gpsLON  ..",Sats no:"..  wgt.gpsSATS..", Alt m:".. wgt.gpsALT ..", Speed kmh:".. wgt.gpsSpeed, "\r\n")					
			io.close(file)			
			--[DEBUG  #####################**
							
			--write logfile		
			file = io.open(log_filename, "a")    									

			io.write(file, wgt.coordinates_current ..",".. time_power_on ..", "..  wgt.gpsSATS..", ".. wgt.gpsALT ..", ".. wgt.gpsSpeed, "\r\n")					
			io.close(file)			

			if wgt.ctr >= 99 then
				wgt.ctr = 0				


_________________________________________________________________
There is no /LOGS/GPS_debug.txt

**Comment by WimSanders** [comment]
[#gps-widget-widgetsgpsmainlua](https://github.com/kristjanbjarni/o
![screen-2023-02-21-174332](https://user-images.githubusercontent.com/24661114/220412451-6f52a916-0bad-4690-ae1c-3158869f1240.gif)
pentx-widgets#gps-widget-widgetsgpsmainlua)
the 2 Lua files avgbatt and GPS work well.

i renamed the GPS to GPS1

![Schermafbeelding 2023-02-21 180759](https://user-images.githubusercontent.com/24661114/220412988-d0013a47-a4ac-4dc9-8a6d-907a4bf832bd.gif)

make a setup of both

![screen-2023-02-21-185451](https://user-images.githubusercontent.com/24661114/220413489-6a16da3a-2c4c-44fc-b7fd-2a08022f045d.gif)

**Comment by moschotto** [comment]
strange?! the other script uses the NAME instead of ID - can you try to change 

	--####################################################################
	--get Latitude, Longitude, Speed and Altitude
	--####################################################################		
       -- wgt.gpsLatLon = getValue(wgt.gpsId)  <= comment this line with two dashes "--"

	wgt.gpsLatLon = getValue("GPS") <= add this

**Comment by moschotto** [comment]
furthermore do you have a sensor called "TMP2" or "Sats"?  this is the sensor where the satellite count / amount comes from!

**IF NOT** the message "no GPS fix" is correct because the script can't read any satellites 
AND
if the satellites count is 2 or lower, no DATA will be displayed at all... no home pos, no current pos etc etc....

**Comment by WimSanders** [comment]
it remains strange that one lua script reads the gps and the other script does not
I have been comparing the 2 lia scrips, in the 2 scripts you read the sensor in different ways

**Comment by WimSanders** [comment]
--####################################################################
--get Latitude, Longitude, Speed and Altitude
--####################################################################		
   -- wgt.gpsLatLon = getValue(wgt.gpsId)  <= comment this line with two dashes "--"

wgt.gpsLatLon = getValue("GPS") <= add this


tomorrow i will try this

**Comment by moschotto** [comment]
> it remains strange that one lua script reads the gps and the other script does not I have been comparing the 2 lia scrips, in the 2 scripts you read the sensor in different ways

=> please read both 2 replies above and double check

**Comment by WimSanders** [comment]
it is already late on my end, tomorrow i will try this

**Comment by WimSanders** [comment]
the sensor I use is an original FR SKY GPS sensor
I've added the line you suggested, it makes no difference.

To check if the number of satellites is a problem I added the following line:

	--####################################################################
	--get number of satellites and GPS fix type
	--####################################################################	
	wgt.gpsSATS = getValue(wgt.gpssatId)
	
	if string.len(wgt.gpsSATS) > 2 then		
		-- SBUS Example 1013: -> 1= GPS fix 0=lowest accuracy 13=13 active satellites
		--[	Sats / Tmp2 : GPS lock status, accuracy, home reset trigger, and number of satellites. Number is sent as ABCD detailed below. Typical minimum 
		--[	A : 1 = GPS fix, 2 = GPS home fix, 4 = home reset (numbers are additive)
		--[	B : GPS accuracy based on HDOP (0 = lowest to 9 = highest accuracy)
		--[	C : number of satellites locked (digit C & D are the number of locked satellites)
		--[ D : number of satellites locked (if 14 satellites are locked, C = 1 & D = 4)		
		wgt.gpsSATS = string.sub (wgt.gpsSATS, 3,6)		
	else
		--CROSSFIRE stores only the active GPS satellite
		wgt.gpsSATS = string.sub (wgt.gpsSATS, 0,3)		
	end	
	-- WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
	wgt.gpsSATS = "4"
	--- WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
	--status message "guess"
	-- 2D Mode - A 2D (two dimensional) position fix that includes only horizontal coordinates. It requires a minimum of three visible satellites.)


Now the display shows 4 satellites but still no data.

**Comment by moschotto** [comment]
please remove the quotes and try again - same position / location where you've already added it 

wgt.gpsSATS = 6      <= it's a number not a string


thats just for testing - again the question,

**furthermore do you have a sensor called "TMP2" or "Sats"? this is the sensor where the satellite count / amount comes from!**



IF NOT the message "no GPS fix" is correct because the script can't read any satellites
AND
if the satellites count is 2 or lower, no DATA will be displayed at all... no home pos, no current pos etc etc....

**Comment by WimSanders** [comment]
you can also try this GPS widget just for testing 
https://github.com/kristjanbjarni/opentx-widgets#gps-widget-widgetsgpsmainlua



This GPS widget works well
is it possible to display the number of satellites in this widget GPS?

**Comment by moschotto** [comment]
then use this widget and ask the guy who programmed it. sorry, but if you don't answer the questions or try what i said then please don't use my widget. i don't have a FR SKY GPS! 

Use Cleafllight or Betaflight, connect the GPS to the flight controller and it should work as expected.

without the information of the satellites (3D fix > 5 satellites) you can't be sure that coordinates that you are seeing on screen are actually correct and therefore it makes no sense to have "random" coordinates on screen.

**Comment by WimSanders** [comment]
I'm sorry, since you recommended this widget, I assumed they were also written by you.
I have learned a lot from studying your widget. I'm familiar with programming in C++, but I've never done anything with lua. Specially the interaction with open TX is completely new to me.

As you may know, the Horus X12 transmitter has its own GPS.
My goal is to show the GPS data from the model aircraft and GPS data from the transmitter on the display. This is very specific Horus X12 so I will have to make part of it myself.

The part of the screen layout with icons in your widget is particularly beautiful. I will certainly copy parts of it (if I may).

Anyway, thanks for all the help you've provided.
As I see it now, my GPS sensor is different from what you are using and I cannot and will not ask you to modify your script to make it work for my sensor and transmitter.

thanks again

**Comment by moschotto** [comment]
it would be helpful if you tell me which telemetry protocol you are using and how everything is connected. 

anyway, if you just want to display coordinates without any sanity checks (like satellite count etc) you have two options:

**Option 1** - set the satellite count to a fixed value i.e. wgt.gpsSATS = 6 

Tested

![image](https://user-images.githubusercontent.com/10543292/220852703-3c0c5ac7-5bbf-416b-8f3f-05d8da6703ba.png)

**Comment by moschotto** [comment]
**Option 2** - change this line

`lcl_drawText(wgt.zone.x + 50,wgt.zone.y + 180, wgt.coordinates_current,LEFT + SMLSIZE ,  newtext_color)`


to

`lcl_drawText(wgt.zone.x + 50,wgt.zone.y + 180, wgt.gpsLAT .. ", " .. wgt.gpsLON,LEFT + SMLSIZE ,  newtext_color)`

![image](https://user-images.githubusercontent.com/10543292/220852989-be43fed3-9495-4006-9554-44f13e7f70bd.png)

**Comment by WimSanders** [comment]
I already suspected that my GPS is not reporting the number of satellites
![screen-2023-02-23-125423](https://user-images.githubusercontent.com/24661114/220887769-b7d5409e-93e6-47ff-bcd4-edeb40ffd840.gif)
![screen-2023-02-23-125901](https://user-images.githubusercontent.com/24661114/220888825-e7157f75-6a59-4103-bf91-624544a6b970.gif)

**Comment by moschotto** [comment]
Ok so it finally “kind of works” now… 

it would be helpful if you tell me which telemetry protocol you are using and how everything is connected.

**Comment by WimSanders** [comment]
where can i find my telemetry protocol?
Does this description help?
Which GPS do you use?
I have sent an email to FR-Sky asking if their GPS reports the number of satellites

[GPS- Manual.pdf](https://github.com/moschotto/OpenTX_GPS_Telemetry/files/10813191/GPS-.Manual.pdf)

**Comment by WimSanders** [comment]
![Schermafbeelding 2023-02-24 133113](https://user-images.githubusercontent.com/24661114/221180061-9706f4d4-82d1-4b9c-8605-0cb3c0dcdb11.gif)
for your information:

**Comment by WimSanders** [comment]
which GPS sensor do you use that does display the number of satellites?

**Comment by moschotto** [comment]
Again - it depends on the protocol you are using. Basically you can use any gps I.e. any ublox M8, M9 etc… I’ve no idea about planes etc and therefore I can’t help you. If you are using a flight controller, check out the telemetry capabilities of the specific software - inav, clean flight, adrupilot, betaflight etc etc
