### ISSUE TITLE
Radiomaster Boxer Install

### ISSUE THREAD

**Issue by mitchponton** [moschotto/OpenTX_GPS_Telemetry#35]
I have installed the Tango 2 lua in the scripts/tools and scripts/telemetry file path with the BMP folder

When I execute the Lua I get the following Syntax Error.

Did I forget something or is this just an issue with Edgetx or the new Radio?

![IMG_20230401_175723](https://user-images.githubusercontent.com/110638115/229330781-64a892b1-c1ee-4295-a70a-566ca0e37e00.jpg)

**Comment by moschotto** [comment]
Radiomaster Boxer is a "Display: 128*64 Monochrome LCD display" radio and supported with EdgeTX 2.8.1

https://oscarliang.com/radiomaster-boxer/

> EdgeTX Firmware Official Support

> EdgeTX 2.8.1 was released on the 18th of Feb 2023 which officially supports the Radiomaster Boxer radio. 


So you probably picked the wrong script. 

The script, at least the "GPSx9L.lua", works in EdgeTX Simulator (v2.8.1) just fine.

![image](https://user-images.githubusercontent.com/10543292/229346566-14232696-c72d-43d7-815e-30ea5efac0a7.png)

![image](https://user-images.githubusercontent.com/10543292/229346706-0e984aa4-bf04-4550-afb3-e1e567515f9b.png)


Please check the install instructions and let me know if it works. Furthermore please let me know the EdgeTX version you are running - other users might have the same issue and can read through this thread.

Thanks

**Comment by mitchponton** [comment]
I was running the 2.8.0 script. I went ahead and redid the scripts with the x9 scripts you posted. Seeing as its such a new and popular radio its nice to have the exact files to post.

On the github main it says to add a screen, is that possible to add a screen to the "home" on the radio where channel monitoring is shown?

Also still getting this syntax error
![IMG_20230402_091320_2](https://user-images.githubusercontent.com/110638115/229374006-7f914bf3-9ec5-4bfc-9337-066f55c9427e.jpg)

**Comment by moschotto** [comment]
Please update the radio - as mentioned above

**Comment by mitchponton** [comment]
> Please update the radio - as mentioned above

Updated to 2.8.1 and put the x9 lua on the radio. Same syntax

**Comment by moschotto** [comment]
since it runs in the simulator just fine and the error on your screen is truncated i've no idea how to solve the problem.

please make sure that you follow the installation instructions closely

- did you create a LOGS folder? <SDCARD root> /LOGS/

- doube check if the GPSpositions.txt is in there, if not, create an empty file in that folder: /LOGS/GPSpositions.txt

- **did you setup a telemetry screen?** via "model settings" => page 12/12?



![image](https://user-images.githubusercontent.com/10543292/229435712-b2ef5ec1-86bc-4b15-806b-b4c4c7ab1317.png)

Update:
you can't "execute" the script from the SDCARD!,- you need to setup a telemetry screen. otherwise you run into the issue:

![image](https://user-images.githubusercontent.com/10543292/229439357-fd8b7353-0a85-4e15-a459-b7b7b1ba3acb.png)

**Comment by mitchponton** [comment]
> since it runs in the simulator just fine and the error on your screen is truncated i've no idea how to solve the problem.
> 
> please make sure that you follow the installation instructions closely
> 
> * did you create a LOGS folder?  /LOGS/
> * doube check if the GPSpositions.txt is in there, if not, create an empty file in that folder: /LOGS/GPSpositions.txt
> * **did you setup a telemetry screen?** via "model settings" => page 12/12?
> 
> ![image](https://user-images.githubusercontent.com/10543292/229435712-b2ef5ec1-86bc-4b15-806b-b4c4c7ab1317.png)
> 
> Update: you can't "execute" the script from the SDCARD!,- you need to setup a telemetry screen. otherwise you run into the issue:
> 
> ![image](https://user-images.githubusercontent.com/10543292/229439357-fd8b7353-0a85-4e15-a459-b7b7b1ba3acb.png)

/LOGS/ is there. I'll double check on the txt file.

I did enable the script on the telemetry page but I didn't do it correctly. I fixed that and it works now! This is absolutely the best.
![received_1666783923767673](https://user-images.githubusercontent.com/110638115/229604571-6825da4c-b7b1-4849-8cc1-058adcbe613a.jpeg)

**Comment by moschotto** [comment]
Ok good to know but why does it look so „broken/scrambled“? The GPSx9L.lua should fit perfectly on screen… see my screenshots in the 2nd post.


You are still using the wrong lua! Pay attention to script name…

**Comment by mitchponton** [comment]
> Ok good to know but why does it look so „broken/scrambled“? The GPSx9L.lua should fit perfectly on screen… see my screenshots in the 2nd post.
> 
> You are still using the wrong lua! Pay attention to script name…

I had removed everything and selected the x9 instead of x9l

Its perfect now and not scrambled.
