### ISSUE TITLE
Radiomaster Zorro 2.7.0 "no GPS data", BetaFlight is OK

### ISSUE THREAD

**Issue by MayanMN** [moschotto/OpenTX_GPS_Telemetry#37]
Hello, I have an issues
config:
Radiomaster Zorro, EdgeTX 2.7.0 
Lua Script GPSx9L
Log file created
Betaflight 4.4
=================
In betflight configurator I can see all data and it's fine, but there is nothing on Zorro's display or log file
page 11/12 there is only 10 sensors ( 1RSS, 2RSS, RQly, RSNR, ANT, RFMD, TPWR, TRSS, TQly, TSNR)

![Screenshot_2023-07-14-17-54-28-405_com runcam android runcambf](https://github.com/moschotto/OpenTX_GPS_Telemetry/assets/139552373/ce2081fb-0548-4b84-a082-88e0de5cec33)
![IMG_20230714_175439](https://github.com/moschotto/OpenTX_GPS_Telemetry/assets/139552373/f2db59a7-ea05-4b85-b6a8-9cd8a21e7bf0)
![IMG_20230714_175523](https://github.com/moschotto/OpenTX_GPS_Telemetry/assets/139552373/863b8ba4-4ede-4f32-8b0b-231311e74784)
![IMG_20230714_175602](https://github.com/moschotto/OpenTX_GPS_Telemetry/assets/139552373/5e94dc2a-a82d-47ba-91f0-8f25da92151d)

**Comment by moschotto** [comment]
Hi,

Make sure GPS, speed, alt sensors have been discovered within the telemetry menu/screen of opentx/edgetx


So if you don’t see the mentioned sensors, the betaflight telemetry is not configured correctly. Check YouTube or the betaflight wiki how to do it. After you see the sensors mentioned above (via “discover new sensors”), try the script again

**Comment by MayanMN** [comment]
Oh my God! 
I checked all ports, speeds, packets and other parameters. I flashed the receiver and transmitter 2 times.
It turned out you just need to enable "Telemetry output" in betaflight.
Whoever encounters a similar problem - start repairs with simple things)
All work great, thanks for your script!
