### ISSUE TITLE
GPS

### ISSUE THREAD

**Issue by sidi996** [moschotto/OpenTX_GPS_Telemetry#38]
Hello,
Frsky X10S Opentx 2.3.15. oXs Sensor with Gps.
Frsky telemetrie Sport  Sats indicates sats 113, script only the last 3. What can i do?
Dieter

**Comment by moschotto** [comment]
Nochmal bitte

**Comment by sidi996** [comment]
Mein GPS Sensor liefert in der Telemetrie z.B. Sats 113, im Widget wird nur die letzte Stelle angezeigt.

**Comment by moschotto** [comment]
`
	
	if string.len(wgt.gpsSATS) > 2 then		
		-- smartport Example 1014: -> 1= GPS fix | 0=lowest accuracy | 14=14 active satellites
		--[	Sats / Tmp2 : GPS lock status, accuracy, home reset trigger, and number of satellites. 
		--[ 	Number is sent as ABCD detailed below. ABCD = 1014
		--[	A : 1 = GPS fix, 2 = GPS home fix, 4 = home reset (numbers are additive)
		--[	B : GPS accuracy based on HDOP (0 = lowest to 9 = highest accuracy)
		--[	C : number of satellites locked (first digit)
		--[ 	D : number of satellites locked (second digit)
		--[ 	for example: "1014"  C = 1 & D = 4 => 14 satellites
		wgt.gpsSATS = string.sub (wgt.gpsSATS, 3,6)		
	else
		--CROSSFIRE stores only the active GPS satellite
		wgt.gpsSATS = string.sub (wgt.gpsSATS, 0,3)		
	end	`



wahrscheinlich weil einfach abgeschnitten wird. welches telemetrie protokoll und welche SW (z.b. betaflight) wird benutzt?

**Comment by sidi996** [comment]
Hallo, 
das  hatte ich angeschaut, komme aber damit nicht zurecht. Muß ich beim Gps suchen, weil der nur drei Stellen liefert.
X10S, opentx 2.3.15, Sport. Kein FC.

Gesendet von Mail für Windows

**Comment by moschotto** [comment]
was bedeutet 113? 113 Satelliten können es ja nicht sein und nochmal die Frage:

welches telemetrie protokoll und welche SW (z.b. betaflight) wird benutzt?

**Comment by sidi996** [comment]
Wie geschrieben frsky X10s mit opentx 2.3.15. Protokoll ist frsky Sport. Kein Betaflight oder sonst etwas.
Ich hatte auch im Frsky Forum nachgefragt, und eine Antwort bekommen.
Offset mit -100 eingeben ....
Funktioniert.
Dieter
Gesendet von Mail für Windows

**Comment by moschotto** [comment]
Ich habe es nicht getestet - einfach mal via Texteditor folgendes austauschen:

Alt:
wgt.gpsSATS = string.sub (wgt.gpsSATS, 0,3)		

Neu:
wgt.gpsSATS =   (wgt.gpsSATS -  (wgt.gpsSATS%10))*0.1

**Comment by sidi996** [comment]
Das versuche ich morgen.Danke für deine HilfeVon meinem iPad gesendetAm 21.07.2023 um 17:41 schrieb moschotto ***@***.***>:﻿
Ich habe es nicht getestet - einfach mal via Texteditor folgendes austauschen:
Alt:
wgt.gpsSATS = string.sub (wgt.gpsSATS, 0,3)
Neu:
wgt.gpsSATS =   (wgt.gpsSATS -  (wgt.gpsSATS%10))*0.1

**Comment by sidi996** [comment]
Gerade noch erfahren: Auszug aus der OXS Description:FILL_TEST1_WITH_GPS_NUMBER_OF_SAT // uncomment to activate this option; note: when there is a GPS fix 3D (or higher), then number of sat is increased by 100Von meinem iPad gesendetAm 21.07.2023 um 17:41 schrieb moschotto ***@***.***>:﻿
Ich habe es nicht getestet - einfach mal via Texteditor folgendes austauschen:
Alt:
wgt.gpsSATS = string.sub (wgt.gpsSATS, 0,3)
Neu:
wgt.gpsSATS =   (wgt.gpsSATS -  (wgt.gpsSATS%10))*0.1
