### ISSUE TITLE
Support for FrSky GPS ADV Sensor

### ISSUE THREAD

**Issue by dylanbeaudette** [moschotto/OpenTX_GPS_Telemetry#39]
Hi,

Thanks for posting this code! It is exactly what I've been looking for. I just gave it a try with my Taranis X9+ (2019) and telemetry generated by this device: https://alofthobbies.com/products/frsky-gps-sensor

The telemetry screen is saying "no GPS data available". I'm wondering if this has something to do with the way in which this device sends coordinates.

More details on my tinkering with this GPS device here:
https://forum.flitetest.com/index.php?threads/limited-gps-coordinate-precision-device-or-frsky-telemetry-limitation.74664/

Any ideas?

Thanks,
Dylan

**Comment by moschotto** [comment]
Hi - might be the same issue than this one (run it through google translate - it’s german ):

https://github.com/moschotto/OpenTX_GPS_Telemetry/issues/38

Let me know if it works

**Comment by moschotto** [comment]
.
