### ISSUE TITLE
Reset sensor now available in OpenTx 2.3.11

### ISSUE THREAD

**Issue by devosthomas** [moschotto/OpenTX_GPS_Telemetry#4]
This could fix the T16 issue...

https://github.com/opentx/opentx/releases/tag/release/2.3.11

LUA
Fix insertMix
Add getColor function
**Add resetSensor function**

**Comment by moschotto** [comment]
reset sensor makes no sense for this kind of issue. widgets are "non" interactive. anyway added a new T16 script with reset functionality

**Comment by devosthomas** [comment]
thanks!
