### ISSUE TITLE
radiomaster pocket cc2500 protocole is not working

### ISSUE THREAD

**Issue by c-mar76** [moschotto/OpenTX_GPS_Telemetry#44]
I recetnly got the radiomaster pocket cc2500, according to this it has a multiprotocole that cannot bind some receivers but not all, I also got some rx from radiomaster as weell (R84, R86, R86C) I could not bind any of them using the internal module
![IMG_20240310_010223 1](https://github.com/moschotto/OpenTX_GPS_Telemetry/assets/163324891/ef4a924d-f354-4e81-aa53-09b2fe4051bd)
can anyone tell me what is wrong here?

**Comment by c-mar76** [comment]
I have also tried also with the other one but they still does
![frsky](https://github.com/moschotto/OpenTX_GPS_Telemetry/assets/163324891/397cfcda-5879-4dfb-83cf-698204b404a9)
 not work

**Comment by moschotto** [comment]
This repository is used for a GPS lua script only. Sorry, no support for any module or radio related issues…
