### ISSUE TITLE
Betafpv radio lite 3 Pro syntax error

### ISSUE THREAD

**Issue by faabbiieenn** [moschotto/OpenTX_GPS_Telemetry#45]
I'm trying to set up gps widget Lua script on my Betafpv radio lite pro 3 (128x64)
![IMG_20240323_210121](https://github.com/moschotto/OpenTX_GPS_Telemetry/assets/164684863/4a875a6d-8eaa-4a61-8337-f83776744e25)
![IMG_20240323_205821](https://github.com/moschotto/OpenTX_GPS_Telemetry/assets/164684863/afdd5140-6410-4f81-a619-50f0cd711bc8)
Please forgive my poor English I'm french😅

**Comment by moschotto** [comment]
Hi, I guess you missed step 4 of the installation instructions

**Comment by faabbiieenn** [comment]
Hy thanks, but it seems that the 9lscript erase all folder as soon as the fix is done, after power off and power on all folder are there!
I use the tango scrip with modified screen (your 9xlite screen) and it works gooood!!

**Comment by faabbiieenn** [comment]
![IMG_20240325_132625](https://github.com/moschotto/OpenTX_GPS_Telemetry/assets/164684863/59ccb852-4a02-4210-9564-3ba7e1020dd3)
![IMG_20240325_132648](https://github.com/moschotto/OpenTX_GPS_Telemetry/assets/164684863/8a537784-4014-41ba-bea2-75a7a2d7f062)
