### ISSUE TITLE
Where do i create the logfile 

### ISSUE THREAD

**Issue by Chillinfpv** [moschotto/OpenTX_GPS_Telemetry#46]
I downloaded and installed the lua script. I discovered the new sensors and they show up in my telemetry screen. But when I try to open the gps stats lua script is says logfiles doesn't exist. Where do I create and put the log files so I can access the lua script.

**Comment by Chillinfpv** [comment]
![20240415_180510](https://github.com/moschotto/OpenTX_GPS_Telemetry/assets/167156065/67299297-0987-4a48-8d3d-a02a06296ae7)

**Comment by Chillinfpv** [comment]
![20240415_204237](https://github.com/moschotto/OpenTX_GPS_Telemetry/assets/167156065/1b097a2b-4488-448c-a1b8-059ecc7527b9)

So I got it reading the satellites count but when I long press enter then back out it doesn't set the home position.

**Comment by moschotto** [comment]
There is only one **big red exclamation mark** in the install instructions. Please double check and try again

**Comment by Chillinfpv** [comment]
So I figured out how to create the GPSpositions.txt file. And put it in the logs folder now I'm getting a syntax error

**Comment by Chillinfpv** [comment]
![20240416_032543](https://github.com/moschotto/OpenTX_GPS_Telemetry/assets/167156065/2ca1093d-aa7e-466d-9d29-6210c27f7288)

**Comment by moschotto** [comment]
As mentioned the GPSpositions.txt will be created automatically by the script (in the directory /LOGS). Just start the telemetry script (not the viewer) and make sure it displays the coordinates => **you have 0**. Once some coordinates have been logged you should see the file with contents in the /LOGS folder. Then you can used the viewer to double check!

Check this video:

https://www.youtube.com/watch?v=3uNYTq7ZAFE

**Comment by Chillinfpv** [comment]
My problem was i didnt know how to create a txt file. I figured thay out and my sensors were messed up. I just deleted em and discovered new. So now I have all the telemetry information but still have a syntax error 
![20240416_142548](https://github.com/moschotto/OpenTX_GPS_Telemetry/assets/167156065/83eb0b08-c2cd-4174-a38a-ae265bff00ef)
![20240416_032543](https://github.com/moschotto/OpenTX_GPS_Telemetry/assets/167156065/d263a2a7-1b17-4499-87fb-3a304e5b00c0)

**Comment by moschotto** [comment]
Again! Delete the gps position txt file

 **the GPSpositions.txt will be created automatically by the script (in the directory /LOGS).**

**Comment by Chillinfpv** [comment]
Awesome thank you! I appreciate you.  That's what I get for receiving help from people who have no idea what they're talking about. I was told to make the txt file and put in it the logs folder
