### ISSUE TITLE
Feature Request - Use getTxGPS() to set home Location if available

### ISSUE THREAD

**Issue by Pelado-Mat** [moschotto/OpenTX_GPS_Telemetry#5]
I have an TX16S with the internalGPS mod so the radio has my current location. It can be access with the lua funcion getTxGPS().

It would be useful that the widget could display the distance and, hopefully, the general direction to the model, but from the current pilot location.

Perhaps merging with this: https://github.com/Hobby4life/Finder ?

**Comment by moschotto** [comment]
„Momentary halted due getTXGPS() bug in OpenTX“

BTW the script is doing what you describe... pilot position (pilot-lat / pilot-lon) is the actually the „home-position“ delivered by the betaflight telemetry. Check the script an you will see it...

https://opentx.gitbooks.io/opentx-2-3-lua-reference-guide/content/general/getValue.html



 I don’t intend to implement a direction pointer/arrow - from my point of view a unnecessary „feature“. Using google maps and the displayed coordinates is much easier and makes more sense than using an arrow with the direction of the model.
