### ISSUE TITLE
Widget Triggers emergency mode on setup

### ISSUE THREAD

**Issue by j-watkiss** [moschotto/OpenTX_GPS_Telemetry#8]
Noticed this today setting up. Specifically in the three view option on a TX16S running 2.3.11 with a 32GB Sandisk card.
Widget works fine when selected for the correct screen view (the larger right hand side) however, setting up other widgets on the two smaller views, scrolling past this widget in the bottom left view triggers emergency mode reliably. Does not prevent use or function provided you don't do this that I have noticed

**Comment by moschotto** [comment]
I don’t own a T16 and therefore I probably won’t change the widget. Maybe if I find time  in the future. As mentioned in the description, the Widget should be used 1/2 screen

**Comment by j-watkiss** [comment]
No worries - if I had the capability I would look into it myself. No major issue, just a little quirk. Ok so long as you dont need a widget which is after this in the queue.

Thanks for your work on this, regardless. A much simpler solution than any we had before

**Comment by moschotto** [comment]
Thx

**Comment by moschotto** [comment]
hi, can you please checkout the newer main.lua in the T16 folder and let me know if this works for you?

Also if the script crashes after setting up and then power off/on the radio?

The simulator seems to work fine, i can't reproduce the _**"scrolling past this widget in the bottom left view triggers emergency mode reliably"**_

![image](https://user-images.githubusercontent.com/10543292/106358340-f61fc780-630b-11eb-8a2b-9804b43ff456.png)


Thanks

**Comment by roligmue** [comment]
Per your request, I loaded the updated script into my Horus X10. It works fine. I did not recreate the widget.                                                            

I will edit per your instructions to change km to miles for my needs. 

Regards

**Comment by moschotto** [comment]
Hi thanks for the reply. Please let me know if you encounter any crashes thanks

**Comment by j-watkiss** [comment]
I will try on tx16s when I get chance

Cheers

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
